apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-config
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: webcontent
      mountPath: /usr/share/nginx/html
  volumes:
  - name: webcontent
    configMap:
      name: nginx-config

